server:
  port: 8080
  error:
    path: /error  # 默认 /error
spring:
  application:
    name: springboot2_admin
  #  mvc:
#    servlet:
  #    path: /mvc
  #    static-path-pattern: /static
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件的大小
      max-request-size: 100MB # 整个请求上传的所有文件的大小
  datasource:
    url: jdbc:mysql://101.35.240.17/ssm
    username: root
    password: 261806
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.chowyijiu.boot.*
      filters: stat, wall # 底层开启功能 stat监控sql wall防火墙
      filter:
        stat:
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false # 不允许删表

      stat-view-servlet:
        enabled: true # 默认true 开启
        login-username: admin # 监控也用户名密码
        login-password: 261806
        reset-enable: false # 是否有重置按钮

      web-stat-filter:
        enabled: true # 默认true 开启
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true # 使用ip注册请求
#配置mybatis规则
#mybatis:
#  # config-location: classpath:mybatis/mybatis-config.xml # 全局配置文件
#  mapper-locations: classpath:mybatis/mapper/*.xml #sql映射文件位置
#  type-aliases-package: com.chowyijiu.boot.bean # bean包
#  configuration:
#    map-underscore-to-camel-case: true #驼峰命名
#    aggressive-lazy-loading: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # 默认值
  type-aliases-package: com.chowyijiu.boot.bean
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    aggressive-lazy-loading: false

# 是所有actuator的配置
management:
  endpoints:
    enabled-by-default: true # 默认开启所有监控端点
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    beans:
      enabled: true
  info:
    env:
      enabled: true

info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@

