server:
  port: 8080
  error:
    path: /error  # 默认 /error
spring:
  mvc:
#    static-path-pattern: /static
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件的大小
      max-request-size: 100MB # 整个请求上传的所有文件的大小